### ISSUE TITLE
Load fails on Windows 10 x64

### ISSUE THREAD

**Issue by ideoma** [urschrei/convertbng#1]
After installation when I try to import:

>>> from convertbng.util import convert_bng
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\convertbng\util.py", line 52, in <module>
    lib = cdll.LoadLibrary(os.path.join('..', file_path, '%slonlat_bng.%s' % (prefix, ext)))
  File "C:\Python27\lib\ctypes\__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found

Windows fails to load lonlat_bng.dll.

Windows 10 x64.

**Comment by urschrei** [comment]
Did you install from pip? Do you get the same error when you try `from convertbng.cutil import convert_bng`?

**Comment by ideoma** [comment]
Yes, installed from pip.

Same error 

C:\repos\datasci>python
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from convertbng.cutil import convert_bng
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: DLL load failed: The specified module could not be found.
>>>

**Comment by urschrei** [comment]
Could you try the latest version from PyPi? (0.4.25?)

-- 
steph

**Comment by urschrei** [comment]
I think the problem is a missing Visual C++ Redistributable, which Rust links against. You can download it for free here: https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by ideoma** [comment]
Installing Redistributes helped
