### ISSUE TITLE
pip install fails on Python 3.9.7 (Sep 16 2021) Windows 10

### ISSUE THREAD

**Issue by Kostas-Konstantinou** [urschrei/convertbng#15]
Collecting convertbng
  Downloading convertbng-0.4.14.tar.gz (11.4 MB)
     |████████████████████████████████| 11.4 MB 6.8 MB/s
Requirement already satisfied: numpy>=1.9.0 in c:\software\anaconda3\lib\site-packages (from convertbng) (1.20.3)
Building wheels for collected packages: convertbng
  Building wheel for convertbng (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\software\Anaconda3\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-ledaapm_\\convertbng_4444f6d4434a49edbac4bacf9b4ff854\\setup.py'"'"'; __file__='"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-ledaapm_\\convertbng_4444f6d4434a49edbac4bacf9b4ff854\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\User\AppData\Local\Temp\pip-wheel-fpqcoz6p'
       cwd: C:\Users\User\AppData\Local\Temp\pip-install-ledaapm_\convertbng_4444f6d4434a49edbac4bacf9b4ff854\
  Complete output (29 lines):
  running bdist_wheel
  The [wheel] section is deprecated. Use [bdist_wheel] instead.
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.9
  creating build\lib.win-amd64-3.9\convertbng
  copying convertbng\util.py -> build\lib.win-amd64-3.9\convertbng
  copying convertbng\__init__.py -> build\lib.win-amd64-3.9\convertbng
  running egg_info
  writing convertbng.egg-info\PKG-INFO
  writing dependency_links to convertbng.egg-info\dependency_links.txt
  writing requirements to convertbng.egg-info\requires.txt
  writing top-level names to convertbng.egg-info\top_level.txt
  reading manifest file 'convertbng.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching 'license.txt'
  warning: no files found matching 'README.md'
  warning: no files found matching 'ostn002_s.gif'
  writing manifest file 'convertbng.egg-info\SOURCES.txt'
  copying convertbng\convertbng_p.pxd -> build\lib.win-amd64-3.9\convertbng
  copying convertbng\cutil.c -> build\lib.win-amd64-3.9\convertbng
  copying convertbng\cutil.pyx -> build\lib.win-amd64-3.9\convertbng
  copying convertbng\liblonlat_bng.dylib -> build\lib.win-amd64-3.9\convertbng
  copying convertbng\liblonlat_bng.so -> build\lib.win-amd64-3.9\convertbng
  copying convertbng\rlib.h -> build\lib.win-amd64-3.9\convertbng
  running build_ext
  building 'convertbng.cutil' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for convertbng
  Running setup.py clean for convertbng
Failed to build convertbng
Installing collected packages: convertbng
    Running setup.py install for convertbng ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\software\Anaconda3\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-ledaapm_\\convertbng_4444f6d4434a49edbac4bacf9b4ff854\\setup.py'"'"'; __file__='"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-ledaapm_\\convertbng_4444f6d4434a49edbac4bacf9b4ff854\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\User\AppData\Local\Temp\pip-record-f99gapzq\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\software\Anaconda3\Include\convertbng'
         cwd: C:\Users\User\AppData\Local\Temp\pip-install-ledaapm_\convertbng_4444f6d4434a49edbac4bacf9b4ff854\
    Complete output (28 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.9
    creating build\lib.win-amd64-3.9\convertbng
    copying convertbng\util.py -> build\lib.win-amd64-3.9\convertbng
    copying convertbng\__init__.py -> build\lib.win-amd64-3.9\convertbng
    running egg_info
    writing convertbng.egg-info\PKG-INFO
    writing dependency_links to convertbng.egg-info\dependency_links.txt
    writing requirements to convertbng.egg-info\requires.txt
    writing top-level names to convertbng.egg-info\top_level.txt
    reading manifest file 'convertbng.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'license.txt'
    warning: no files found matching 'README.md'
    warning: no files found matching 'ostn002_s.gif'
    writing manifest file 'convertbng.egg-info\SOURCES.txt'
    copying convertbng\convertbng_p.pxd -> build\lib.win-amd64-3.9\convertbng
    copying convertbng\cutil.c -> build\lib.win-amd64-3.9\convertbng
    copying convertbng\cutil.pyx -> build\lib.win-amd64-3.9\convertbng
    copying convertbng\liblonlat_bng.dylib -> build\lib.win-amd64-3.9\convertbng
    copying convertbng\liblonlat_bng.so -> build\lib.win-amd64-3.9\convertbng
    copying convertbng\rlib.h -> build\lib.win-amd64-3.9\convertbng
    running build_ext
    building 'convertbng.cutil' extension
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\software\Anaconda3\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-ledaapm_\\convertbng_4444f6d4434a49edbac4bacf9b4ff854\\setup.py'"'"'; __file__='"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-ledaapm_\\convertbng_4444f6d4434a49edbac4bacf9b4ff854\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\User\AppData\Local\Temp\pip-record-f99gapzq\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\software\Anaconda3\Include\convertbng' Check the logs for full command output.

**Comment by urschrei** [comment]
I'm currently unable to provide installable packages for Windows, and I don't know when I'll be able to fix the problem. Sorry!

**Comment by Kostas-Konstantinou** [comment]
Hi

Many thanks for the quick reply. 

Best
Kostas

**Comment by urschrei** [comment]
Now available for Windows 64-bit on PyPI: https://pypi.org/project/convertbng/#files

**Comment by damarislanders** [comment]
Hello, I think this may be erroring again. Thank you.

```

Collecting convertbng
  Using cached convertbng-0.4.14.tar.gz (11.4 MB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy>=1.9.0 in c:\users\hert6836\appdata\local\programs\python\python311\lib\site-packages (from convertbng) (1.24.2)
Installing collected packages: convertbng
  DEPRECATION: convertbng is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for convertbng ... error
  error: subprocess-exited-with-error

  × Running setup.py install for convertbng did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      running install
      C:\Users\hert6836\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\convertbng
      copying convertbng\util.py -> build\lib.win-amd64-cpython-311\convertbng
      copying convertbng\__init__.py -> build\lib.win-amd64-cpython-311\convertbng
      running egg_info
      writing convertbng.egg-info\PKG-INFO
      writing dependency_links to convertbng.egg-info\dependency_links.txt
      writing requirements to convertbng.egg-info\requires.txt
      writing top-level names to convertbng.egg-info\top_level.txt
      reading manifest file 'convertbng.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching 'license.txt'
      warning: no files found matching 'README.md'
      warning: no files found matching 'ostn002_s.gif'
      writing manifest file 'convertbng.egg-info\SOURCES.txt'
      copying convertbng\convertbng_p.pxd -> build\lib.win-amd64-cpython-311\convertbng
      copying convertbng\cutil.c -> build\lib.win-amd64-cpython-311\convertbng
      copying convertbng\cutil.pyx -> build\lib.win-amd64-cpython-311\convertbng
      copying convertbng\liblonlat_bng.dylib -> build\lib.win-amd64-cpython-311\convertbng
      copying convertbng\liblonlat_bng.so -> build\lib.win-amd64-cpython-311\convertbng
      copying convertbng\rlib.h -> build\lib.win-amd64-cpython-311\convertbng
      running build_ext
      building 'convertbng.cutil' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> convertbng

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

**Comment by urschrei** [comment]
> error: Microsoft Visual C++ 14.0 or greater is required.

Have you installed Microsoft C++ Build Tools from https://visualstudio.microsoft.com/visual-cpp-build-tools/ ?
