### ISSUE TITLE
Python 3.7 binary wheel for PyPI

### ISSUE THREAD

**Issue by snorfalorpagus** [urschrei/convertbng#3]
Is it possible to get a build for Python 3.7 on PyPI?

I've done a build locally and it seems to pass all of the tests.

**Comment by urschrei** [comment]
IApparently I can't build a Windows wheel for 3.7 yet, because there doesn't appear to be an Anaconda 3.7 distribution on Appveyor, but there's now a macOS wheel available (0.6.5)…was that the platform you were hoping for?

**Comment by snorfalorpagus** [comment]
Thanks! Is it possible to do one for Linux also? We're deploying it as part of an application in a Docker container.

**Comment by urschrei** [comment]
Ah, I should have checked, there's a 3.7 `manylinux1` wheel on PyPI too. Let me know if it's working for you.

**Comment by urschrei** [comment]
Now available on PyPI as v0.6.9 for Windows 32- and 64-bit Python 3.7
