### ISSUE TITLE
Minor documentation typo

### ISSUE THREAD

**Issue by Yorkshire-Jack** [urschrei/convertbng#4]
Minor issue with the readme.md. It currently gives the bounding box as

> **Latitude:**
> East: 1.7800
> West: -7.5600
> **Longitude:**
> North: 60.8400
> South: 49.9600

But "Latitude" and "Longitude" are the wrong way around.

**Comment by Yorkshire-Jack** [comment]
Additionally, under **Available Conversions (AKA I Want To…)** the readme lists `convert_etrs89` which does not appear to exist. It may have been renamed?

**Comment by urschrei** [comment]
Hm yes that's…not good. The swapped coordinates have been fixed in the README, and `convert_to_etrs89` is now available from `util` and `cutil` in v0.6.10, on PyPI.
